### ISSUE TITLE
Does not work with released version of Thorpy 

### ISSUE THREAD

**Issue by lordmauve** [YannThorimbert/everglide#1]
The released version of Thorpy does not provide some of the functions that this game requires. I also don't see these in the Thorpy GitHub repo:

```
Traceback (most recent call last):
  File "everglide/main.py", line 653, in <module>
    thorpy.set_default_font(FONT)
AttributeError: module 'thorpy' has no attribute 'set_default_font'
```

```
Traceback (most recent call last):
  File "everglide/main.py", line 659, in <module>
    e_goal = thorpy.make_textbox_nobutton("Goal",
AttributeError: module 'thorpy' has no attribute 'make_textbox_nobutton'
```

**Comment by YannThorimbert** [comment]
Thanks for the message.
Yes, I added some lines to the library while coding the game, this is why the zip file provided with the game contains a modified Thorpy version.

The modifications will probably be included in the library with the next commit.

**Comment by lordmauve** [comment]
Ohhhhhhhh, your ZIP file contains two copies of your game code, one in the root of the zip in `main.py` and the other in the `everglide` folder in `run_game.py`. Only the `run_game.py` version works.
